### ISSUE TITLE
Fix occasional panic on shutdown

### ISSUE THREAD

**Issue by Koshroy** [nolanlum/tanya#33]
Occasionally on shutdown I receive a panic:
```
panic: close of closed channel
goroutine 19 [running]:
github.com/nolanlum/tanya/irc.(*Server).waitForKillListener(0xc4201141b0, 0xc42017e000)
        ~/src/go/src/github.com/nolanlum/tanya/irc/server.go:118 +0x1c0
created by github.com/nolanlum/tanya/irc.(*Server).Listen
       ~/src/go/src/github.com/nolanlum/tanya/irc/server.go:67 +0x2ce
```

**Comment by nolanlum** [comment]
This was fixed by `d5c86c81d69d36b89fb2f0284ea69c2de5e35716`
