### ISSUE TITLE
ParseMessageTextWithOptions panic on `nolanlum/track-inflight`

### ISSUE THREAD

**Issue by nolanlum** [nolanlum/tanya#65]
panic: runtime error: index out of range [0] with length 0

```
goroutine 13 [running]:
github.com/nolanlum/tanya/gateway.(*SlackClient).ParseMessageTextWithOptions(0xc0000c0360, 0xc000120640, 0x47, 0xc00011d900, 0x0, 0x0)
        C:/Users/Nolan Lum/go/src/github.com/nolanlum/tanya/gateway/message_parser.go:30 +0x1528
github.com/nolanlum/tanya/gateway.(*SlackClient).ParseMessageText(...)
        C:/Users/Nolan Lum/go/src/github.com/nolanlum/tanya/gateway/message_parser.go:13
github.com/nolanlum/tanya/gateway.(*SlackClient).handleMessageEvent(0xc0000c0360, 0xc00001a2a0, 0xc00007c780)
        C:/Users/Nolan Lum/go/src/github.com/nolanlum/tanya/gateway/message_handler.go:76 +0x12b
github.com/nolanlum/tanya/gateway.(*SlackClient).Poop(0xc0000c0360, 0xc00000d4c0)
        C:/Users/Nolan Lum/go/src/github.com/nolanlum/tanya/gateway/slack.go:545 +0x93e
created by main.launchGateway
        C:/Users/Nolan Lum/go/src/github.com/nolanlum/tanya/main.go:232 +0xd6
```

**Comment by nolanlum** [comment]
can't reproduce xd
